# Generated by Django 6.0.6 on 2026-06-25 12:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='image',
            field=models.ImageField(upload_to='uploads/categories/'),
        ),
        migrations.CreateModel(
            name='ItemsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='uploads/items/')),
                ('is_available', models.BooleanField(default=False)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('stock', models.IntegerField(default=1)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_store.categorymodel')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
    ]
