# Generated by Django 6.0.6 on 2026-06-26 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0002_alter_categorymodel_image_itemsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsmodel',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itemsmodel',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
