# Generated by Django 6.0.6 on 2026-06-27 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0003_itemsmodel_is_featured_alter_itemsmodel_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='online_store.categorymodel'),
        ),
    ]
